CREATE TABLE "SYSTEM"."DS_USER" 
   (	"USER_ID" NUMBER(*,0) NOT NULL ENABLE, 
	"UNAME" VARCHAR2(100 BYTE) NOT NULL ENABLE, 
	"UMAILID" VARCHAR2(100 BYTE) NOT NULL ENABLE, 
	"UMOB" NUMBER(*,0) NOT NULL ENABLE, 
	"USOCIALFBID" VARCHAR2(50 BYTE), 
	"USOCIALGID" VARCHAR2(50 BYTE), 
	"ISACTIVE" VARCHAR2(2 BYTE), 
	"ISLOGGEDIN" VARCHAR2(2 BYTE), 
	"ISLOGGEDINSOCIAL" VARCHAR2(2 BYTE), 
	"PASSWORD" VARCHAR2(50 BYTE), 
	"USOCIALFB" VARCHAR2(255 CHAR)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;